install:
 pip install -r requirements.txt

run:
 uvicorn app.main:app --reload

test:
 pytest -v

docker-up:
 docker compose up --build

docker-down:
 docker compose down

docker-logs:
 docker compose logs -f